### ISSUE TITLE
Some `slow-odgi` tests failing

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/pollen#119]
Probably minor, but something bad has slipped through. It should not be too hard to dive in and check where things went awry. It happened in the last couple days for sure.

_Originally posted by @anshumanmohan in https://github.com/cucapra/pollen/issues/118#issuecomment-1634672473_

**Comment by susan-garry** [comment]
After updating `turnt` via `python3.9 -m pip install turnt --upgrade`, more of the tests are passing than before, but all of the `flip` and `validate` tests are failing! In both cases, there seems to be an issue with links getting dropped. Here are the diffs for `note5.gfa`:

Flip:
```
--- test/note5.flip	2023-07-13 00:13:02.639008800 -0400
+++ /tmp/tmp2grt3jme	2023-07-13 14:14:10.173015133 -0400
@@ -5,7 +5,3 @@
 S	4	TCTCAGG
 P	5	1+,3+,4+	*
 P	5-	1+,3-,4+	*
-L	1	+	3	-	0M
-L	1	+	3	+	0M
-L	3	-	4	+	0M
-L	3	+	4	+	0M
```

Validate:

```
--- test/note5.validate	2023-07-12 23:47:57.249831362 -0400
+++ /tmp/tmpr7k6mmy9	2023-07-13 14:44:22.553493140 -0400
@@ -0,0 +1,4 @@
+[odgi::validate] error: the path 5 does not respect the graph topology: the link 1+,3+ is missing.
+[odgi::validate] error: the path 5 does not respect the graph topology: the link 3+,4+ is missing.
+[odgi::validate] error: the path 5- does not respect the graph topology: the link 1+,3- is missing.
+[odgi::validate] error: the path 5- does not respect the graph topology: the link 3-,4+ is missing.
```

**Comment by sampsyo** [comment]
That's odd! I will look into this more deeply, but one quick thing to try: just rerun `make slow-odgi-setup ; make slow-odgi-oracles` to ensure that all the auxiliary files are up to date?

**Comment by anshumanmohan** [comment]
Susan is your `slow-odgi` itself current? Do you need to run `path/to/pollen/slow_odgi$ python3 -m pip install --user -e ../mygfa .`?

**Comment by anshumanmohan** [comment]
I just ran this on Havarti using the latest turnt and the following commit of `odgi`:
```
/path/to/odgi$ git show --oneline -s
7b09e802 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #500 from aryarm/master
```

1. `test-slow-odgi` worked cleanly.
2. I noticed, however, that this was not running all the targets under `slow-odgi-tests`. It was running the first only, not all four.
      ```
      slow-odgi-tests:
	      turnt -j $(TEST_ENVS:%=--env %) test/*.gfa
	      turnt -j --env validate_test_err test/invalid/*.gfa
	      turnt -j --env crush_test test/handmade/crush*.gfa
	      turnt -j --env flip_test test/handmade/flip*.gfa
      ```
3. I ran the other three by hand. While `flip` and `crush` worked great, I had an issue with `invalid`: 
      ```
      not ok 1 - test/invalid/chr6.C4.gfa validate_test_err
      # exit code: 0, expected: 1
      ```
    I had this for all eight files. The fix was to go into turnt.toml and change the environment `validate_test_err`. I don't think it needs the `return_code = 1` flag, because `slow-odgi` currently considers it a _graceful_ run if it is passed an invalid graph and it can point out issues with the validity of the graph.

**Comment by anshumanmohan** [comment]
@sampsyo please let me know if you can recreate this! The fact that it's running only part of the recipe seems very strange to me, and I'm 90% sure that it's me who's being silly, not `make`.

**Comment by sampsyo** [comment]
Oops; thanks for pointing out the issue where we weren't running everything! And the problem with the `invalid` tests expecting the wrong error code, which was masked by that. PR incoming shortly!
