### ISSUE TITLE
`pollen_data_gen`: support for `subset_paths`

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/pollen#137]
@susan-garry points out that `pollen_data_gen` does not currently support `subset_paths`, which gets in the way of it being a drop-in replacement for the existing ODGI-dependent code. See also, https://github.com/cucapra/pollen/issues/129. 

Susan explored the space, saying that we have two options:
- Feed it a `subset_paths` files along with the GFA graph.
    - Pro: Simpler
    - Con: seems to violate the principle that `pollen_data_gen` should be precisely a representation of information in a GFA file.
- Leave it as it is, i.e., make it just just a GFA. Then add an extra step to splice in the information about `subset_paths`.
    - Pro: Keeps the layers separate.
    - Con: More complex.  

We have decided to go with the first option.

**Comment by sampsyo** [comment]
Nice! Sounds perfectly reasonable to me.
