### ISSUE TITLE
slow-odgi: points of divergence and confusion

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/pollen#32]
- [x] Match `odgi flip` behavior.
This could come from changes on our end, or by triggering further changes in odgi's code or spec. 
Basically I think there is still a bug in `odgi flip`. Andrea made a fix for me, and this helped in one spot, but introduced an issue elsewhere. See [here](https://github.com/pangenome/odgi/pull/485#issuecomment-1496693803) if curious.

- [ ] Figure out `odgi inject`. 
  - [x] Understand it. 
  I can't recreate the stated behavior of `odgi inject` even for trivial requests. I have asked on Matrix; see [here](https://matrix.to/#/!gfJejgcqPPoQQwBTPY:matrix.org/$QtUIJcktjgfVqVn1_CB8LJOFxtRLMVUhrRbXGh9PcVE?via=matrix.org).
  - [ ] Support it in `slow-odgi`.
- [x] Check with Andrea et al if `odgi overlap` is coded up correctly.
    I _can_ recreate the behavior of `odgi overlap`, but I think they mean to calculate something more subtle and in fact have a bug. I have asked on Matrix; see [here](https://matrix.to/#/!gfJejgcqPPoQQwBTPY:matrix.org/$tngcETjHFpEqLZA9vZS4PcJT77LNjIUWZfpB3eX2tY8?via=matrix.org).
- [x] Figure out what's going on in `odgi groom`. See [this](https://github.com/cucapra/pollen/commit/a2807ebc0f25b8a065ebd8a60311705aed8dd926#r105820995) comment if you're curious. 
  - [x] Make a minimal example.
  - [x] Ask about it on Matrix.

**Comment by anshumanmohan** [comment]
Updates: 
2. Got some clarity re: `odgi inject`. Will just get it done quickly.
3. Also got some clarity re: `odgi overlap`, but this has led to a [new question](https://matrix.to/#/!gfJejgcqPPoQQwBTPY:matrix.org/$VV5L5oW-XjFpL-cEJLSZ31Eiyl_dwAJc-g62f8P7TvI?via=matrix.org): how to issue nontrivial flavors of this command?

**Comment by sampsyo** [comment]
Wow! Thank you for centralizing this "tracking" issue for understanding the bits of odgi we are currently confused about! This will be really useful to have.

This is very superficial and process-related, but one useful thing to do in this kind of GitHub issue is to edit the issue description to have checkboxes, like this:

* [ ] match `odgi flip` behavior
* [ ] figure out what's going on with `odgi groom`
* [ ] …

This way, it's easy to see that, when all the checkboxes are checked, the issue is done. It's like a little mini progress meter within the scope of a tracking issue.

**Comment by anshumanmohan** [comment]
I finally understand how to invoke `odgi overlap` in interesting ways! A basic invocation is correctly replicated already and that's been merged in, but at some point I'll flesh it out some more.

Here's the deal.

Say I have a graph:
```
S 1 ATGC...(* a seq of length 90 *)
S 2 ATGC...(* a seq of length 10 *)
S 3 ATGC...(* a seq of length 90 *)
P x 1+,2+
P y 2+,3+
L ... (* nothing special *)
```

If I query `overlap` with just the names of the paths, i.e. with flag -R and the file
```
x
y
```
I'll get that x overlaps with y and y with x. Fine.

The more interesting query is to specify _ranges_ within the query path. So, for example:
- "path x, start 0, end 50" will _not_ return y;
- "path x, start 0, end 100" _will_;
- "path x, start 92, end 95" will as well.

The way to specify these ranges is via a special kind of BED file, a little different from the kind we have generated previously using `flatten`. So I'd run `overlap` with the -b flag and the following file.
```
x    0    30
```

**Comment by anshumanmohan** [comment]
I'm assuming that `slow-odgi flip` will not converge with `odgi flip` in the next few days, so I've checked it off here and moved it to #46, the parking lot for the next version. See there for more details!
