### ISSUE TITLE
slow-odgi: more thoughtful generation of segment names

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/pollen#54]
It doesn't seem like segment names are guaranteed to be numbers in the GFA format. They are in all the examples we're familiar with, but it seems to me like the format defines them to be arbitrary strings (which is why we store them as `str`s and not `int`s). Therefore:

* `int(seg.name)` is not guaranteed to succeed
* `str(int(seg.name) + 1)` is not guaranteed to be unique

Longer term, we probably want to generate a "fresh" name by looking at all the existing names and generating one that is actually guaranteed to be unused. Or perhaps we want to use some kind if internal numeric ID space, which we then map back to strings. Anyway, plenty of options here!

_Originally posted by @sampsyo in https://github.com/cucapra/pollen/pull/51#discussion_r1170651606_

**Comment by anshumanmohan** [comment]
Today I discovered that `odgi build` dies if you try to name a segment non-numerically. 
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stol
make: *** [Makefile:150: test/note5.og] Aborted (core dumped)
```

**Comment by sampsyo** [comment]
Wow, how about that! Good to know. So maybe we shouldn't bother doing anything about this?

**Comment by anshumanmohan** [comment]
Yeah I think so. At least for now, while odgi is the oracle and odgi functionality is the target, I think this issue is moot. If/when we decide to graduate from odgi-style commands and allow pangenome-ey commands more generally, we could revisit this.
