### ISSUE TITLE
README is stale

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/pollen#86]
The top-level Pollen README does not work as written. I think the issues are small, FWIW!

Is it literally just that `flit install -s --user` needs to be run not from `pollen/` but from `pollen/pollen-py/`?

_Originally posted by @anshumanmohan in https://github.com/cucapra/pollen/issues/83#issuecomment-1538949521_

**Comment by anshumanmohan** [comment]
Is it literally just that `flit install -s --user` needs to be run not from `pollen/` but from `pollen/pollen-py/`?

**Comment by susan-garry** [comment]
You're absolutely right! I went ahead and committed the change directly to the main branch since it's only one line, but feel free to polish it up if you think it could be improved further

**Comment by anshumanmohan** [comment]
Many thanks!!
