### ISSUE TITLE
Examples of Pollen

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/pollen#93]
It would amazing to have (pseudo-)Pollen implementations of the commands that we currently support in [`slow_odgi`](https://github.com/cucapra/pollen/tree/main/slow_odgi). I know Priya is on it; I just wanted to make an issue so we can track it and get excited!!

**Comment by anshumanmohan** [comment]
There is another planned outage coming up — @priyasrikumar and I will be at OPLSS — and it would be great to get this done before we leave so that @susan-garry can test the parser against these. Priya, possible?

**Comment by priyasrikumar** [comment]
Hey! There are a few [examples](https://github.com/cucapra/pollen/blob/examples/slow_odgi/examples.md) in the `examples` branch that can hopefully kickstart the parser testing. I can definitely commit to getting in at least 2-3 more examples, if not all 5, before PLDI/OPLSS.
